const mercury = {
    name: 'Mercury',
    distanceToSun: '57.9 million km',
    rotationSpeed: '10.83 km/s',
    volume: '6.083 x 10^10 km³',
    temperature: '430°C',
    diameter: '4,880 km',
    gravity: '3.7 m/s²',
    atmosphere: 'Thin atmosphere, mostly helium and hydrogen',
    moons: 'None',
    rings: 'None',
    magneticField: 'Weak magnetic field',
    dayLength: '58.6 Earth days',
    yearLength: '88 Earth days',
    discovery: 'Known to ancient civilizations',
    composition: 'Rocky, iron-rich',
    surfaceFeatures: 'Craters and plains',
    axialTilt: '0.034°',
    escapeVelocity: '4.3 km/s',
    meanDensity: '5.427 g/cm³',
    orbitalSpeed: '47.87 km/s',
  };
  
  const venus = {
    name: 'Venus',
    distanceToSun: '108.2 million km',
    rotationSpeed: '6.52 km/s',
    volume: '9.284 x 10^11 km³',
    temperature: '471°C',
    diameter: '12,104 km',
    gravity: '8.87 m/s²',
    atmosphere: 'Thick atmosphere, mainly carbon dioxide',
    moons: 'None',
    rings: 'None',
    magneticField: 'Weak magnetic field',
    dayLength: '116 Earth days',
    yearLength: '225 Earth days',
    discovery: 'Known to ancient civilizations',
    composition: 'Rocky with a metal core',
    surfaceFeatures: 'Volcanoes and highland regions',
    axialTilt: '177.3°',
    escapeVelocity: '10.36 km/s',
    meanDensity: '5.243 g/cm³',
    orbitalSpeed: '35.02 km/s',
  };
  
  const earth = {
    name: 'Earth',
    distanceToSun: '149.6 million km',
    rotationSpeed: '1670 km/h',
    volume: '1.08321 x 10^12 km³',
    temperature: '15°C',
    diameter: '12,742 km',
    gravity: '9.81 m/s²',
    atmosphere: 'Nitrogen, oxygen, argon, and other trace gases',
    moons: 'One (the Moon)',
    rings: 'None',
    magneticField: 'Moderate magnetic field',
    dayLength: '24 hours',
    yearLength: '365.25 days',
    discovery: 'Known to ancient civilizations',
    composition: 'Rocky with a metal core',
    surfaceFeatures: 'Mountains, oceans, and diverse landscapes',
    axialTilt: '23.5°',
    escapeVelocity: '11.2 km/s',
    meanDensity: '5.513 g/cm³',
    orbitalSpeed: '29.78 km/s',
  };
  
  const mars = {
    name: 'Mars',
    distanceToSun: '227.9 million km',
    rotationSpeed: '868.22 km/h',
    volume: '1.6318 x 10^11 km³',
    temperature: '-80°C',
    diameter: '6,779 km',
    gravity: '3.71 m/s²',
    atmosphere: 'Thin atmosphere, mostly carbon dioxide',
    moons: 'Phobos and Deimos',
    rings: 'None',
    magneticField: 'Weak magnetic field',
    dayLength: '1.03 Earth days',
    yearLength: '687 Earth days',
    discovery: 'Known to ancient civilizations',
    composition: 'Rocky, iron-rich',
    surfaceFeatures: 'Olympus Mons, the largest volcano in the solar system',
    axialTilt: '25.2°',
    escapeVelocity: '5.03 km/s',
    meanDensity: '3.933 g/cm³',
    orbitalSpeed: '24.07 km/s',
  };
  
  const jupiter = {
    name: 'Jupiter',
    distanceToSun: '778.5 million km',
    rotationSpeed: '12.6 km/s',
    volume: '1.43128 x 10^15 km³',
    temperature: '-145°C',
    diameter: '139,820 km',
    gravity: '24.79 m/s²',
    atmosphere: 'Primarily hydrogen and helium',
    moons: '79 known moons, including Ganymede (largest) and Io (volcanically active)',
    rings: 'Yes, a system of rings',
    magneticField: 'Strongest magnetic field in the solar system',
    dayLength: '9.9 Earth hours',
    yearLength: '11.86 Earth years',
    discovery: 'Known to ancient civilizations',
    composition: 'Primarily gas and liquid metallic hydrogen',
    surfaceFeatures: 'Giant storms, including the Great Red Spot',
    axialTilt: '3.1°',
    escapeVelocity: '59.5 km/s',
    meanDensity: '1.326 g/cm³',
    orbitalSpeed: '13.07 km/s',
  };
  
  const saturn = {
    name: 'Saturn',
    distanceToSun: '1.43 billion km',
    rotationSpeed: '9.87 km/s',
    volume: '8.2713 x 10^14 km³',
    temperature: '-178°C',
    diameter: '116,460 km',
    gravity: '10.44 m/s²',
    atmosphere: 'Primarily hydrogen and helium',
    moons: '83 known moons, including Titan (largest) and Enceladus',
    rings: 'Yes, the most prominent ring system in the solar system',
    magneticField: 'Strong magnetic field',
    dayLength: '10.7 Earth hours',
    yearLength: '29.46 Earth years',
    discovery: 'Known to ancient civilizations',
    composition: 'Primarily gas and liquid metallic hydrogen',
    surfaceFeatures: 'Distinctive ring system and hexagonal polar storm',
    axialTilt: '26.7°',
    escapeVelocity: '35.5 km/s',
    meanDensity: '0.687 g/cm³',
    orbitalSpeed: '9.68 km/s',
  };
  
  const uranus = {
    name: 'Uranus',
    distanceToSun: '2.87 billion km',
    rotationSpeed: '2.59 km/s',
    volume: '6.833 x 10^13 km³',
    temperature: '-224°C',
    diameter: '50,724 km',
    gravity: '8.69 m/s²',
    atmosphere: 'Hydrogen, helium, and methane',
    moons: '27 known moons, including Titania and Oberon',
    rings: 'Yes, a system of rings',
    magneticField: 'Unique sideways (tilted) magnetic field',
    dayLength: '17.2 Earth hours',
    yearLength: '84.02 Earth years',
    discovery: 'Discovered by William Herschel in 1781',
    composition: 'Primarily ice and rock',
    surfaceFeatures: 'Subtle cloud patterns and a blue-green hue',
    axialTilt: '97.8°',
    escapeVelocity: '21.3 km/s',
    meanDensity: '1.27 g/cm³',
    orbitalSpeed: '6.8 km/s',
  };
  
  const neptune = {
    name: 'Neptune',
    distanceToSun: '4.5 billion km',
    rotationSpeed: '5.43 km/s',
    volume: '6.254 x 10^13 km³',
    temperature: '-218°C',
    diameter: '49,244 km',
    gravity: '11.15 m/s²',
    atmosphere: 'Hydrogen, helium, and methane',
    moons: '14 known moons, including Triton and Proteus',
    rings: 'Yes, a system of faint rings',
    magneticField: 'Strong magnetic field',
    dayLength: '16.1 Earth hours',
    yearLength: '164.8 Earth years',
    discovery: 'Discovered by Johann Galle in 1846',
    composition: 'Primarily ice and rock',
    surfaceFeatures: 'Dynamic and evolving storm systems',
    axialTilt: '28.3°',
    escapeVelocity: '23.5 km/s',
    meanDensity: '1.638 g/cm³',
    orbitalSpeed: '5.43 km/s',
  };
  
  export { mercury, venus, earth, mars, jupiter, saturn, uranus, neptune };
  
  