// Star Objects
let sun = {
    name: "Sun",
    type: "G-type main-sequence star",
    mass: "1.989 × 10^30 kg",
    radius: "696,340 km",
    temperature: "15 million degrees Celsius",
    luminosity: "3.8 × 10^26 W",
    age: "4.6 billion years",
    composition: "Hydrogen, Helium, trace elements",
    distanceFromEarth: "149.6 million km",
    constellation: "N/A",
    discovered: "N/A",
    galaxies: "Milky Way",
    solarSystem: "Yes",
    planets: 8,
    moons: "N/A",
    spectralClass: "G2V",
    rotationPeriod: "25 days",
    magneticField: "Yes",
    solarWind: "Yes",
    prominences: "Yes",
  };
  
  let sirius = {
    name: "Sirius",
    type: "A-type main-sequence star",
    mass: "2.02 × 10^30 kg",
    radius: "1.711 × 10^6 km",
    temperature: "9,940 degrees Celsius",
    luminosity: "25.4 L☉",
    age: "200 to 300 million years",
    composition: "Hydrogen, Helium",
    distanceFromEarth: "8.6 light-years",
    constellation: "Canis Major",
    discovered: "Ancient times",
    galaxies: "Milky Way",
    solarSystem: "No",
    planets: 0,
    moons: "N/A",
    spectralClass: "A1V",
    rotationPeriod: "5.4 days",
    magneticField: "Yes",
    solarWind: "Yes",
    prominences: "Yes",
  };
  
  let alphaCentauri = {
    name: "Alpha Centauri",
    type: "Triple star system",
    mass: "2.185 × 10^30 kg",
    radius: "2.22 × 10^6 km",
    temperature: "5,500 degrees Celsius",
    luminosity: "1.519 L☉",
    age: "6 billion years",
    composition: "Primarily Hydrogen, Helium",
    distanceFromEarth: "4.37 light-years",
    constellation: "Centaurus",
    discovered: "Ancient times",
    galaxies: "Milky Way",
    solarSystem: "No",
    planets: "At least 1",
    moons: "N/A",
    spectralClass: "G2V",
    rotationPeriod: "N/A",
    magneticField: "N/A",
    solarWind: "N/A",
    prominences: "N/A",
  };
  
  let betelgeuse = {
    name: "Betelgeuse",
    type: "Red supergiant",
    mass: "8.58 × 10^31 kg",
    radius: "1,180 times that of the Sun",
    temperature: "3,500 degrees Celsius",
    luminosity: "100,000 L☉",
    age: "8 to 8.5 million years",
    composition: "Primarily Hydrogen",
    distanceFromEarth: "640 light-years",
    constellation: "Orion",
    discovered: "Ancient times",
    galaxies: "Milky Way",
    solarSystem: "No",
    planets: "N/A",
    moons: "N/A",
    spectralClass: "M1-M2Ia-Iab",
    rotationPeriod: "N/A",
    magneticField: "N/A",
    solarWind: "N/A",
    prominences: "Yes",
  };
  
  let vega = {
    name: "Vega",
    type: "A-type main-sequence star",
    mass: "2.135 × 10^30 kg",
    radius: "2.362 × 10^6 km",
    temperature: "9,600 degrees Celsius",
    luminosity: "40.12 L☉",
    age: "455 million years",
    composition: "Hydrogen, Helium",
    distanceFromEarth: "25 light-years",
    constellation: "Lyra",
    discovered: "Ancient times",
    galaxies: "Milky Way",
    solarSystem: "No",
    planets: "N/A",
    moons: "N/A",
    spectralClass: "A0Va",
    rotationPeriod: "12.5 hours",
    magneticField: "Yes",
    solarWind: "Yes",
    prominences: "N/A",
  };
  
 export {sun,sirius,alphaCentauri,betelgeuse,vega}
 
  